import { ProjectStatus, type Project, type Service, type ServicePackage } from "@prisma/client";

const now = new Date("2026-06-10T10:00:00.000Z");

export const demoServices: Service[] = [
  { id: "demo-service-1", name: "Echipe dedicate", description: "Ingineri integrați în ritmul companiei tale, cu procese clare de livrare și raportare.", icon: "Users", features: ["Recrutare tehnică atentă", "Management de livrare", "Scalare rapidă"], order: 1, active: true, createdAt: now, updatedAt: now },
  { id: "demo-service-2", name: "Dezvoltare aplicații web", description: "Platforme moderne pentru operațiuni, vânzări și experiențe digitale stabile.", icon: "Globe2", features: ["Next.js și React", "API-uri securizate", "Performanță măsurabilă"], order: 2, active: true, createdAt: now, updatedAt: now },
  { id: "demo-service-3", name: "Modernizare software", description: "Refactorizare, migrare și înlocuire treptată a sistemelor vechi fără întreruperi majore.", icon: "RefreshCcw", features: ["Audit arhitectural", "Migrare cloud", "Reducerea datoriei tehnice"], order: 3, active: true, createdAt: now, updatedAt: now },
  { id: "demo-service-4", name: "Soluții cloud", description: "Infrastructură pregătită pentru creștere, monitorizare și lansări previzibile.", icon: "Cloud", features: ["AWS, Azure, GCP", "CI/CD", "Observabilitate"], order: 4, active: true, createdAt: now, updatedAt: now },
  { id: "demo-service-5", name: "QA și testare", description: "Strategii de calitate pentru aplicații critice, de la testare manuală la automatizare.", icon: "ShieldCheck", features: ["Teste end-to-end", "Regresie automată", "Planuri de calitate"], order: 5, active: true, createdAt: now, updatedAt: now },
  { id: "demo-service-6", name: "Consultanță digitală", description: "Clarificăm produsul, arhitectura și pașii tehnici înainte de investiții mari.", icon: "Lightbulb", features: ["Analiză tehnică inițială", "Plan de produs", "Estimări realiste"], order: 6, active: true, createdAt: now, updatedAt: now },
  { id: "demo-service-7", name: "Aplicații mobile", description: "Experiențe mobile pentru echipe, clienți și parteneri, conectate la sisteme sigure.", icon: "Smartphone", features: ["React Native", "Design accesibil", "Publicare asistată"], order: 7, active: true, createdAt: now, updatedAt: now },
  { id: "demo-service-8", name: "Integrare sisteme", description: "Conectăm CRM, ERP, plăți, analitice și servicii interne prin API-uri robuste.", icon: "Network", features: ["Integrări B2B", "Automatizări", "Sincronizare date"], order: 8, active: true, createdAt: now, updatedAt: now },
];

export const demoProjects: Project[] = [
  {
    id: "demo-project-1",
    title: "Platformă B2B pentru achiziții industriale",
    slug: "platforma-b2b-achizitii-industriale",
    description: "Portal de autoservire pentru cereri de ofertă, fluxuri de aprobare și raportare comercială.",
    industry: "Producție",
    clientChallenge: "Clientul gestiona cererile prin email și fișiere separate, iar aprobările întârziau comenzile importante.",
    solution: "Am construit o platformă web cu roluri, catalog personalizat, aprobări pe praguri valorice și integrare ERP.",
    results: "Timpul mediu de procesare a scăzut cu 42%, iar echipa comercială are vizibilitate zilnică asupra cererilor active.",
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Azure"],
    imageUrl: "/brand/project-industrial.svg",
    category: "Platforme web",
    status: ProjectStatus.PUBLISHED,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-project-2",
    title: "Aplicație pentru managementul programărilor medicale",
    slug: "management-programari-medicale",
    description: "Sistem digital pentru clinici cu programări, notificări și fișe operaționale pentru personal.",
    industry: "Sănătate",
    clientChallenge: "Recepția folosea instrumente diferite pentru programări, confirmări și rapoarte, ceea ce producea erori.",
    solution: "Am livrat o aplicație securizată cu calendar unificat, notificări automate și exporturi operaționale.",
    results: "Rata de neprezentare a scăzut cu 28%, iar timpul de coordonare pentru recepție s-a redus semnificativ.",
    technologies: ["React", "Express", "PostgreSQL", "Docker"],
    imageUrl: "/brand/project-health.svg",
    category: "Sisteme operaționale",
    status: ProjectStatus.PUBLISHED,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-project-3",
    title: "Modernizare portal e-commerce regional",
    slug: "modernizare-portal-ecommerce-regional",
    description: "Migrare graduală către o arhitectură modernă pentru catalog, checkout și promoții.",
    industry: "Comerț online",
    clientChallenge: "Platforma existentă era greu de întreținut, iar lansarea campaniilor necesita intervenții manuale.",
    solution: "Am separat modulele critice, am optimizat performanța paginilor și am introdus fluxuri automate de lansare.",
    results: "Paginile principale au devenit cu 55% mai rapide, iar echipa lansează campanii fără blocaje tehnice.",
    technologies: ["Next.js", "Prisma", "Stripe", "AWS"],
    imageUrl: "/brand/project-commerce.svg",
    category: "Modernizare",
    status: ProjectStatus.PUBLISHED,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-project-4",
    title: "Tablou financiar pentru analiză de portofoliu",
    slug: "dashboard-financiar-analiza-portofoliu",
    description: "Interfață analitică pentru indicatori de risc, rapoarte și alerte de portofoliu.",
    industry: "Finanțe",
    clientChallenge: "Analiștii pregăteau rapoarte manual, cu date din mai multe surse și verificări repetate.",
    solution: "Am integrat sursele de date, am definit indicatorii critici și am creat vizualizări pentru decizii rapide.",
    results: "Rapoartele săptămânale sunt generate în aceeași zi, iar abaterile importante sunt semnalate automat.",
    technologies: ["TypeScript", "Node.js", "PostgreSQL", "Power BI"],
    imageUrl: "/brand/project-finance.svg",
    category: "Date și raportare",
    status: ProjectStatus.PUBLISHED,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoPackages: ServicePackage[] = [
  { id: "demo-package-1", name: "Start tehnic", description: "Pentru companii care vor validare rapidă și un plan clar de execuție.", price: "de la 3.500 EUR", duration: "2-4 săptămâni", deliverables: ["Audit tehnic", "Plan de arhitectură", "Estimare de buget"], targetIndustries: ["SaaS", "Comerț online", "Servicii profesionale"], cta: "Programează analiza", createdAt: now, updatedAt: now },
  { id: "demo-package-2", name: "Echipă dedicată", description: "Pentru dezvoltare continuă cu specialiști integrați în procesele tale.", price: "ofertă lunară personalizată", duration: "minimum 3 luni", deliverables: ["Ingineri dedicați", "Coordonator tehnic", "Raportare săptămânală"], targetIndustries: ["Fintech", "Sănătate", "Producție"], cta: "Cere o echipă", createdAt: now, updatedAt: now },
  { id: "demo-package-3", name: "Livrare completă", description: "Pentru produse sau module livrate cap-coadă pe un obiectiv definit.", price: "buget fix după analiză", duration: "8-16 săptămâni", deliverables: ["Design funcțional", "Dezvoltare", "QA și lansare"], targetIndustries: ["Retail", "Logistică", "Educație"], cta: "Discută proiectul", createdAt: now, updatedAt: now },
];
